# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addphoto.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPhotoDlg(object):
    def setupUi(self, AddPhotoDlg):
        AddPhotoDlg.setObjectName("AddPhotoDlg")
        AddPhotoDlg.resize(400, 300)
        AddPhotoDlg.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddPhotoDlg)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(AddPhotoDlg)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbSelectedFile = QtWidgets.QLabel(self.frame)
        self.lbSelectedFile.setGeometry(QtCore.QRect(20, 10, 70, 13))
        self.lbSelectedFile.setObjectName("lbSelectedFile")
        self.leSelectedFile = QtWidgets.QLineEdit(self.frame)
        self.leSelectedFile.setGeometry(QtCore.QRect(90, 10, 241, 20))
        self.leSelectedFile.setObjectName("leSelectedFile")
        self.tbSelectPhoto = QtWidgets.QToolButton(self.frame)
        self.tbSelectPhoto.setGeometry(QtCore.QRect(340, 10, 25, 19))
        self.tbSelectPhoto.setObjectName("tbSelectPhoto")
        self.lbNewFileName = QtWidgets.QLabel(self.frame)
        self.lbNewFileName.setGeometry(QtCore.QRect(20, 70, 70, 13))
        self.lbNewFileName.setObjectName("lbNewFileName")
        self.leNewFileName = QtWidgets.QLineEdit(self.frame)
        self.leNewFileName.setGeometry(QtCore.QRect(90, 70, 160, 20))
        self.leNewFileName.setObjectName("leNewFileName")
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddPhotoDlg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddPhotoDlg)
        self.buttonBox.accepted.connect(AddPhotoDlg.accept) # type: ignore
        self.buttonBox.rejected.connect(AddPhotoDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddPhotoDlg)

    def retranslateUi(self, AddPhotoDlg):
        _translate = QtCore.QCoreApplication.translate
        self.lbSelectedFile.setText(_translate("AddPhotoDlg", "Select file"))
        self.tbSelectPhoto.setText(_translate("AddPhotoDlg", "..."))
        self.lbNewFileName.setToolTip(_translate("AddPhotoDlg", "New file name without extension"))
        self.lbNewFileName.setText(_translate("AddPhotoDlg", "New file name"))
